export {
  createAdminFAQ,
  createAdminFoodProvider,
  createAdminRouteSegment,
  createAdminTestimonial,
  createAdminTransportRoute,
  deleteAdminFAQ,
  deleteAdminFoodProvider,
  deleteAdminRouteSegment,
  deleteAdminTestimonial,
  deleteAdminTransportRoute,
  getAdminFAQs,
  getAdminFoodProviders,
  getAdminRouteSegments,
  getAdminTestimonials,
  getAdminTransportRoutes,
  getFAQs,
  getFoodProvider,
  getFoodProviders,
  getRouteSegments,
  getTestimonials,
  getTransportRoutes,
  updateAdminFAQ,
  updateAdminFoodProvider,
  updateAdminRouteSegment,
  updateAdminTestimonial,
  updateAdminTransportRoute,
} from "@/lib/api/final-crud";

export type {
  FAQ,
  FoodProvider,
  RouteSegment,
  Testimonial,
  TransportRoute,
} from "@/lib/api/final-crud";
