name: pahuna-frontend

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5050}
        SERVER_API_URL: http://pahuna-backend:5050
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3001}
        MISTRAL_API_KEY: ${MISTRAL_API_KEY:-}
        MISTRAL_MODEL: ${MISTRAL_MODEL:-mistral-small-latest}
    container_name: pahuna-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    networks:
      - pahuna-net
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5050}
      SERVER_API_URL: http://pahuna-backend:5050
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3001}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY:-}
      MISTRAL_MODEL: ${MISTRAL_MODEL:-mistral-small-latest}

networks:
  pahuna-net:
    external: true
