export type NavItem = {
  label: string;
  href: string;
};

export type FeatureCard = {
  title: string;
  slug?: string;
  eyebrow?: string;
  description: string;
  href: string;
  image?: string;
  meta?: string;
};

export type StayCard = {
  slug: string;
  name: string;
  type: string;
  typeLabel?: string;
  area: string;
  district: string;
  address?: string;
  priceFrom?: string;
  priceValue?: number;
  currency?: string;
  rating?: number;
  reviewCount?: number;
  verified?: boolean;
  featured?: boolean;
  publicListing?: boolean;
  verificationStatus?: "VERIFIED" | "PARTNER" | "PUBLIC_LISTING" | "PENDING";
  consentStatus?: "APPROVED" | "PENDING";
  shortDescription?: string;
  longDescription?: string;
  amenities: string[];
  services?: string[];
  image: string;
  gallery?: string[];
  googleMapLink?: string;
  latitude?: number;
  longitude?: number;
};

export type FoodProvider = {
  slug: string;
  name: string;
  type: string;
  typeLabel: string;
  area: string;
  district: string;
  address?: string;
  shortDescription: string;
  longDescription?: string;
  image: string;
  gallery?: string[];
  cuisines: string[];
  services: string[];
  features: string[];
  priceLevel?: "Budget" | "Moderate" | "Premium";
  openingHours?: string;
  rating?: number;
  reviewCount?: number;
  featured?: boolean;
  verificationStatus?: "VERIFIED" | "PARTNER" | "PUBLIC_LISTING" | "PENDING";
  googleMapLink?: string;
};

export const navItems: NavItem[] = [
  { label: "Explore Surkhet", href: "/explore" },
  { label: "Stays", href: "/hotels" },
  { label: "Food", href: "/food" },
  { label: "Destinations", href: "/destinations" },
  { label: "Trip Planner", href: "/trip-planner" },
  { label: "Contact", href: "/contact" },
];

export const images = {
  hero: "/images/karnali/aakashe-tal-jumla.jpg",
  karnaliHero: "/images/hero/karnali-hero.jpg",
  bulbule: "/images/surkhet/bulbule-lake.jpg",
  kakrebihar: "/images/surkhet/kakrebihar.jpg",
  kakrebiharAlt: "/images/surkhet/kakrebihar-2.jpg",
  deutiBajai: "/images/surkhet/deuti-bajai-2.jpg",
  ghantaghar: "/images/surkhet/ghantaghar-surkhet-4.jpg",
  gurase: "/images/surkhet/gurase-view-tower.jpg",
  stadium: "/images/surkhet/karnali-stadium.jpg",
  bheriBridge: "/images/surkhet/bheri-river-bridge.jpg",
  ranimatta: "/images/surkhet/ranimatta.jpg",
  nightView: "/images/surkhet/surkhet-night-view.jpg",
  rara: "/images/karnali/rara-lake.jpg",
  phoksundo: "/images/karnali/phoksundo-lake.jpg",
  kupinde: "/images/karnali/kupinde-daha.jpg",
  karnaliRiver: "/images/karnali/karnali-river.jpg",
  bheriRiver: "/images/karnali/bheri-river.jpg",
  tharuCulture: "/images/experiences/tharu-cultural-evening.jpg",
  paragliding: "/images/experiences/paragliding-surkhet.jpg",
  camping: "/images/experiences/camping.jpg",
  cycling: "/images/experiences/cycling.jpg",
  horseRiding: "/images/experiences/horse-riding.jpg",
  food: "/images/experiences/tharu-cultural-evening.jpg",
  cafe: "/images/surkhet/ghantaghar-surkhet-5.jpg",
  tea: "/images/karnali/apple-jumla.jpg",
  restaurant: "/images/food/restaurant-placeholder.svg",
  momo: "/images/food/momo-placeholder.svg",
  coffee: "/images/food/cafe-placeholder.svg",
  lounge: "/images/food/bar-lounge-placeholder.svg",
  eventFood: "/images/food/event-restaurant-placeholder.svg",
  stay: "/images/surkhet/surkhet-night-view.jpg",
  hotelFallback: "/images/placeholders/stay-placeholder.svg",
  foodFallback: "/images/placeholders/food-placeholder.svg",
  destinationFallback: "/images/placeholders/destination-placeholder.svg",
  routeFallback: "/images/karnali/bheri-corridor-jajarkot.jpg",
};

export function safeImage(image?: string, fallback = images.destinationFallback) {
  return image?.trim() || fallback;
}

export const quickActions: FeatureCard[] = [
  {
    title: "Explore Surkhet",
    description: "Places, routes, stays, food, and local tips from one clean guide.",
    href: "/explore",
    meta: "Main gateway",
  },
  {
    title: "Find a stay",
    description: "Browse hotels, resorts, lodges, homestays, and public listings.",
    href: "/hotels",
    meta: "Stays",
  },
  {
    title: "Find food & cafes",
    description: "Cafes, local restaurants, momo spots, and family food stops.",
    href: "/food",
    meta: "Food",
  },
  {
    title: "Explore destinations",
    description: "Surkhet, Rara, Phoksundo, Dailekh, Jumla, and wider Karnali.",
    href: "/destinations",
    meta: "Places",
  },
  {
    title: "Plan a trip",
    description: "Turn your days, route, and budget into a simple travel plan.",
    href: "/trip-planner",
    meta: "Planner",
  },
  {
    title: "Estimate route/cost",
    description: "Preview route difficulty, transport options, and practical costs.",
    href: "/trip-planner#routes",
    meta: "Cost",
  },
  {
    title: "Send inquiry",
    description: "Ask about availability, routes, food stops, or local support.",
    href: "/contact",
    meta: "Help",
  },
];

export const surkhetPlaces: FeatureCard[] = [
  {
    title: "Bulbule Lake",
    eyebrow: "Lake walk",
    description: "A calm Surkhet stop for family walks, local snacks, and easy evening plans.",
    href: "/explore#bulbule-lake",
    image: images.bulbule,
  },
  {
    title: "Kakrebihar",
    eyebrow: "Culture",
    description: "Historic ruins, forest surroundings, and one of Surkhet's strongest heritage anchors.",
    href: "/explore#kakrebihar",
    image: images.kakrebihar,
  },
  {
    title: "Deuti Bajai",
    eyebrow: "Temple",
    description: "A respected local spiritual site often included in short Surkhet itineraries.",
    href: "/explore#deuti-bajai",
    image: images.deutiBajai,
  },
  {
    title: "Ghantaghar",
    eyebrow: "City icon",
    description: "A simple city landmark for first-time visitors exploring Birendranagar.",
    href: "/explore#ghantaghar",
    image: images.ghantaghar,
  },
  {
    title: "Gurase View Tower",
    eyebrow: "Viewpoint",
    description: "Cooler hill air, long views, and a clean short escape from Surkhet valley.",
    href: "/explore#gurase-view-tower",
    image: images.gurase,
  },
  {
    title: "Bheri River Bridge",
    eyebrow: "Route moment",
    description: "A practical route marker and scenic stop on regional Karnali movement.",
    href: "/explore#bheri-river-bridge",
    image: images.bheriBridge,
  },
];

export const featuredStays: StayCard[] = [
  {
    slug: "hotel-suva-surkhet",
    name: "Hotel Suva Surkhet",
    type: "Hotel",
    typeLabel: "City Hotel",
    area: "Birendranagar",
    district: "Surkhet",
    address: "Birendranagar city core",
    priceFrom: "Rs. 4,800/night",
    priceValue: 4800,
    currency: "NPR",
    rating: 4.6,
    reviewCount: 42,
    verified: true,
    featured: true,
    publicListing: true,
    verificationStatus: "PARTNER",
    consentStatus: "APPROVED",
    shortDescription: "A practical city stay for travelers who want quick access to Surkhet markets, food, and onward Karnali transport.",
    longDescription: "Hotel Suva Surkhet is presented as a traveler-friendly Birendranagar base for city access, family stays, and route planning before moving toward Dailekh, Jumla, Rara, or Dolpa. Availability, room category, and pricing should be confirmed through inquiry.",
    amenities: ["Wi-Fi", "Restaurant", "Parking", "Family rooms"],
    services: ["Stay inquiry", "Route support", "Breakfast"],
    image: images.nightView,
    gallery: [images.nightView, images.ghantaghar, images.bheriBridge],
    googleMapLink: "https://maps.google.com/?q=Hotel+Suva+Surkhet",
    latitude: 28.6019,
    longitude: 81.6339,
  },
  {
    slug: "siddhartha-sunny-resort",
    name: "Siddhartha Sunny Resort",
    type: "Resort",
    typeLabel: "Resort",
    area: "Birendranagar",
    district: "Surkhet",
    address: "Surkhet valley",
    priceFrom: "Rs. 6,500/night",
    priceValue: 6500,
    currency: "NPR",
    rating: 4.7,
    reviewCount: 38,
    verified: true,
    featured: true,
    publicListing: true,
    verificationStatus: "VERIFIED",
    consentStatus: "APPROVED",
    shortDescription: "A resort-style Surkhet stay for families, events, and travelers who prefer a softer landing before Karnali routes.",
    longDescription: "Siddhartha Sunny Resort is shown as a premium Surkhet base with resort-style comfort, suitable for families, groups, and guests planning onward movement. Confirm current rooms, events, and dining options before booking.",
    amenities: ["Garden", "Restaurant", "Parking", "Event space"],
    services: ["Family stay", "Group inquiry", "Dining"],
    image: images.ranimatta,
    gallery: [images.ranimatta, images.nightView, images.karnaliHero],
    googleMapLink: "https://maps.google.com/?q=Siddhartha+Sunny+Resort+Surkhet",
    latitude: 28.6034,
    longitude: 81.6287,
  },
  {
    slug: "hotel-de-namaste-surkhet",
    name: "Hotel De Namaste Surkhet",
    type: "Hotel",
    typeLabel: "Business Hotel",
    area: "Birendranagar",
    district: "Surkhet",
    address: "Main market area",
    priceFrom: "Rs. 4,200/night",
    priceValue: 4200,
    currency: "NPR",
    rating: 4.4,
    reviewCount: 29,
    verified: true,
    featured: true,
    publicListing: true,
    verificationStatus: "PUBLIC_LISTING",
    consentStatus: "PENDING",
    shortDescription: "A central public listing for travelers who want market access and simple stay coordination.",
    longDescription: "Hotel De Namaste Surkhet is kept as a public listing with practical city positioning. Direct commercial details should be confirmed through Pahuna inquiry until verification is complete.",
    amenities: ["City access", "Restaurant", "Wi-Fi", "Transport nearby"],
    services: ["Stay inquiry", "Market access", "Transit stay"],
    image: images.ghantaghar,
    gallery: [images.ghantaghar, images.nightView, images.bulbule],
    googleMapLink: "https://maps.google.com/?q=Hotel+De+Namaste+Surkhet",
  },
  {
    slug: "valley-view-resort",
    name: "Valley View Resort",
    type: "Resort",
    typeLabel: "View Resort",
    area: "Birendranagar",
    district: "Surkhet",
    address: "Surkhet valley edge",
    priceFrom: "Rs. 5,500/night",
    priceValue: 5500,
    currency: "NPR",
    rating: 4.8,
    reviewCount: 24,
    verified: true,
    featured: true,
    publicListing: true,
    verificationStatus: "VERIFIED",
    consentStatus: "APPROVED",
    shortDescription: "A scenic stay option for travelers who want a calm Surkhet base with valley context.",
    longDescription: "Valley View Resort fits travelers who want a quieter Surkhet stay before or after longer Karnali movement. Confirm room type, meal timing, and transport needs before final booking.",
    amenities: ["Parking", "Family rooms", "Restaurant", "Valley view"],
    services: ["Stay inquiry", "Meals", "Family stay"],
    image: images.nightView,
    gallery: [images.nightView, images.ranimatta, images.bheriBridge],
    googleMapLink: "https://maps.google.com/?q=Birendranagar+Surkhet",
  },
  {
    slug: "bulbule-heritage-inn",
    name: "Bulbule Heritage Inn",
    type: "Hotel",
    typeLabel: "Lake Area Hotel",
    area: "Bulbule",
    district: "Surkhet",
    address: "Near Bulbule Lake",
    priceFrom: "Rs. 3,800/night",
    priceValue: 3800,
    currency: "NPR",
    rating: 4.3,
    reviewCount: 18,
    verified: true,
    publicListing: true,
    verificationStatus: "PUBLIC_LISTING",
    consentStatus: "PENDING",
    shortDescription: "A lake-area listing for easy evening walks and simple family-friendly Surkhet plans.",
    longDescription: "Bulbule Heritage Inn is positioned around Bulbule Lake for visitors who want a calm local stop. Confirm exact facilities and availability through inquiry.",
    amenities: ["Near lake", "Wi-Fi", "Breakfast", "Family rooms"],
    services: ["Stay inquiry", "Breakfast", "Lake access"],
    image: images.bulbule,
    gallery: [images.bulbule, images.bheriBridge, images.ghantaghar],
    googleMapLink: "https://maps.google.com/?q=Bulbule+Lake+Surkhet",
  },
  {
    slug: "kakrebihar-guest-house",
    name: "Kakrebihar Guest House",
    type: "Guest House",
    typeLabel: "Guest House",
    area: "Latikoili",
    district: "Surkhet",
    address: "Kakrebihar area",
    priceFrom: "Ask price",
    priceValue: 0,
    verified: false,
    publicListing: true,
    verificationStatus: "PUBLIC_LISTING",
    consentStatus: "PENDING",
    shortDescription: "A simple guest-house style listing near Surkhet heritage and forest surroundings.",
    longDescription: "Kakrebihar Guest House is useful for travelers prioritizing heritage stops and quiet local areas. It is a public listing and should be verified through inquiry before planning around it.",
    amenities: ["Local host", "Quiet area", "Simple rooms", "Heritage nearby"],
    services: ["Local host", "Simple stay", "Heritage access"],
    image: images.kakrebiharAlt,
    gallery: [images.kakrebiharAlt, images.kakrebihar, images.deutiBajai],
    googleMapLink: "https://maps.google.com/?q=Kakrebihar+Surkhet",
  },
  {
    slug: "gurase-hill-stay",
    name: "Gurase Hill Stay",
    type: "Homestay",
    typeLabel: "Hill Homestay",
    area: "Gurase",
    district: "Dailekh / Surkhet route",
    address: "Gurase route",
    priceFrom: "Ask availability",
    priceValue: 0,
    verified: false,
    publicListing: true,
    verificationStatus: "PUBLIC_LISTING",
    consentStatus: "PENDING",
    shortDescription: "A route-side homestay idea for hill air, tea stops, and short Gurase movement.",
    longDescription: "Gurase Hill Stay is a route-style public listing for travelers who prefer hill weather and local meals. Availability, access, and exact location should be confirmed before departure.",
    amenities: ["Viewpoint", "Tea stop", "Local meals", "Cool climate"],
    services: ["Homestay inquiry", "Local meals", "Route stop"],
    image: images.gurase,
    gallery: [images.gurase, images.gurase, images.bheriBridge],
    googleMapLink: "https://maps.google.com/?q=Gurase+View+Tower",
  },
  {
    slug: "rara-gateway-lodge",
    name: "Rara Gateway Lodge",
    type: "Lodge",
    typeLabel: "Route Lodge",
    area: "Surkhet onward route",
    district: "Karnali route",
    address: "Rara route planning stop",
    priceFrom: "Ask availability",
    priceValue: 0,
    rating: 4.1,
    reviewCount: 11,
    verified: false,
    publicListing: true,
    verificationStatus: "PENDING",
    consentStatus: "PENDING",
    shortDescription: "A route-planning lodge concept for travelers preparing a Surkhet to Rara journey.",
    longDescription: "Rara Gateway Lodge is included as a route-facing public listing. It helps users compare stay types for longer Karnali movement without inventing exact room availability.",
    amenities: ["Route advice", "Simple rooms", "Meal inquiry", "Transport coordination"],
    services: ["Route stay", "Rara planning", "Meal inquiry"],
    image: images.rara,
    gallery: [images.rara, images.karnaliRiver, images.bheriBridge],
    googleMapLink: "https://maps.google.com/?q=Rara+route+Surkhet",
  },
  {
    slug: "bheri-riverside-camp",
    name: "Bheri Riverside Camp",
    type: "Lodge",
    typeLabel: "Riverside Camp",
    area: "Bheri corridor",
    district: "Surkhet / Jajarkot route",
    address: "Bheri corridor",
    priceFrom: "Ask availability",
    priceValue: 0,
    rating: 4.2,
    reviewCount: 9,
    verified: false,
    publicListing: true,
    verificationStatus: "PUBLIC_LISTING",
    consentStatus: "PENDING",
    shortDescription: "A route-side camp listing for Bheri corridor travelers and adventure groups.",
    longDescription: "Bheri Riverside Camp is a public planning listing for travelers considering river-route movement. Confirm safety, season, group support, and meals before planning around it.",
    amenities: ["Riverside", "Group inquiry", "Meals", "Route support"],
    services: ["Adventure stay", "Group support", "Food inquiry"],
    image: images.bheriRiver,
    gallery: [images.bheriRiver, images.bheriBridge, images.camping],
    googleMapLink: "https://maps.google.com/?q=Bheri+River+Surkhet",
  },
  {
    slug: "dailekh-route-homestay",
    name: "Dailekh Route Homestay",
    type: "Homestay",
    typeLabel: "Local Homestay",
    area: "Dailekh route",
    district: "Dailekh",
    address: "Surkhet to Dailekh road",
    priceFrom: "Ask host",
    priceValue: 0,
    verified: false,
    publicListing: true,
    verificationStatus: "PUBLIC_LISTING",
    consentStatus: "PENDING",
    shortDescription: "A local homestay listing for cultural route extensions from Surkhet to Dailekh.",
    longDescription: "Dailekh Route Homestay supports travelers considering a slower cultural extension. It remains inquiry-based until host details and availability are verified.",
    amenities: ["Local meals", "Host family", "Route stop", "Cultural access"],
    services: ["Homestay inquiry", "Local food", "Route support"],
    image: images.deutiBajai,
    gallery: [images.deutiBajai, images.gurase, images.karnaliRiver],
    googleMapLink: "https://maps.google.com/?q=Dailekh+Nepal",
  },
];

const supplementalStaySeeds: StayCard[] = [
  ["highlands-cafe-motel-inn", "Highlands Cafe & Motel Inn", "Hotel", "Khajura-8, Birendranagar"],
  ["tacoma-the-garden-resort", "Tacoma The Garden Resort", "Resort", "Birendranagar-3, Hilekhali"],
  ["namaste-hotel-birendranagar-6", "Namaste Hotel", "Hotel", "Birendranagar-6, Bazaar"],
  ["hotel-namaste-nepal", "Hotel Namaste Nepal", "Hotel", "Pipal Chautara, Birendranagar"],
  ["oyo-705-hotel-de-namaste", "OYO 705 Hotel De Namaste", "Hotel", "Buddha Path"],
  ["oyo-758-hotel-atithi-hotel-atithi", "OYO 758 Hotel Atithi", "Hotel", "Buddha Path"],
  ["hotel-new-athiti", "Hotel New Athiti", "Hotel", "Buddhapath"],
  ["hotel-darshan", "Hotel Darshan", "Hotel", "Birendranagar"],
  ["nirvana-hotel-and-resorts-surkhet", "Nirvana Hotel And Resorts Surkhet", "Resort", "Birendranagar"],
  ["hotel-bulbule-view-2", "Hotel Bulbule View 2", "Hotel", "Bulbule"],
  ["stay-hotel-valley-view-resort", "Stay Hotel Valley View Resort", "Resort", "Surkhet valley"],
  ["hotel-valley-view", "Hotel Valley View", "Hotel", "Birendranagar"],
  ["subedi-hotel-and-lodge", "Subedi Hotel and Lodge", "Lodge", "Birendranagar"],
  ["sumeru-hotel-with-step-inn-restaurant-bar", "Sumeru Hotel with Step Inn Restaurant & Bar", "Hotel", "Birendranagar"],
  ["shirsthan-hotel-restaurant", "Shirsthan Hotel & Restaurant", "Hotel", "Surkhet"],
  ["new-satkar-hotel-restaurant", "New Satkar Hotel & Restaurant", "Hotel", "Surkhet"],
  ["hotel-panchakoshi", "Hotel Panchakoshi", "Hotel", "Surkhet"],
  ["ganesh-hotel-lodge", "Ganesh Hotel & Lodge", "Lodge", "Surkhet"],
  ["manakamana-hotel-lodge", "Manakamana Hotel & Lodge", "Lodge", "Surkhet"],
  ["kasturi-guest-house", "Kasturi Guest House", "Guest House", "Surkhet"],
  ["hotel-the-new-vision", "Hotel The New Vision", "Hotel", "Birendranagar"],
  ["hotel-city-view-surkhet", "Hotel City View Surkhet", "Hotel", "Surkhet"],
  ["aama-ko-bhansa-ghar-inn-pvt-ltd", "Aama ko Bhansa Ghar Inn Pvt. Ltd.", "Inn", "Surkhet"],
  ["peace-land-guest-house", "Peace Land Guest House", "Guest House", "Surkhet"],
  ["dads-pride-resort-guranshe-dads-pride-pvt-ltd", "Dad's Pride Resort Guranshe", "Resort", "Guranshe"],
  ["rara-eco-resort-hotel-rara", "Rara Eco Resort / Hotel Rara", "Resort", "Rara route"],
  ["rara-village-resort", "Rara Village Resort", "Resort", "Rara route"],
  ["rara-resort-rara-murma-home-stay", "Rara Resort & Rara Murma Home Stay", "Homestay", "Rara route"],
].map(([slug, name, type, area], index) => ({
  slug,
  name,
  type,
  typeLabel: type,
  area,
  district: area.includes("Rara") ? "Mugu / Karnali route" : area.includes("Guranshe") ? "Dailekh / Surkhet route" : "Surkhet",
  address: area,
  priceFrom: "Ask availability",
  priceValue: 0,
  verified: false,
  publicListing: true,
  verificationStatus: "PUBLIC_LISTING",
  consentStatus: "PENDING",
  shortDescription: `${name} is part of Pahuna's reference stay catalogue for travelers comparing Surkhet and Karnali route options.`,
  longDescription: `${name} is included as an inquiry-first public listing adapted from the Pahuna reference data. Confirm room availability, price, contact permission, and facilities before final booking.`,
  amenities: ["Stay inquiry", "Local access", "Traveler support", index % 3 === 0 ? "Restaurant inquiry" : "Availability check"],
  services: ["Accommodation inquiry", "Route planning support", "Direct confirmation"],
  image: [images.bulbule, images.ghantaghar, images.nightView, images.gurase, images.rara][index % 5],
  gallery: [
    [images.bulbule, images.kakrebihar, images.ghantaghar][index % 3],
    [images.nightView, images.gurase, images.bheriBridge][index % 3],
    [images.rara, images.karnaliRiver, images.deutiBajai][index % 3],
  ],
  googleMapLink: `https://maps.google.com/?q=${encodeURIComponent(`${name} ${area}`)}`,
}));

const staySlugSet = new Set(featuredStays.map((stay) => stay.slug));
featuredStays.push(...supplementalStaySeeds.filter((stay) => !staySlugSet.has(stay.slug)));

export const foodProviders: FoodProvider[] = [
  {
    slug: "local-thakali-family-restaurants",
    name: "Local Thakali & Family Restaurants",
    type: "Restaurant",
    typeLabel: "Family Restaurant",
    area: "Birendranagar",
    district: "Surkhet",
    address: "Birendranagar city area",
    shortDescription: "Rice sets, local meals, and family-friendly food stops before longer Karnali routes.",
    longDescription: "This listing groups traveler-friendly Thakali and family restaurant options around Birendranagar. Menu, opening hours, and group dining should be confirmed through inquiry.",
    image: images.food,
    gallery: [images.food, images.restaurant, images.bulbule],
    cuisines: ["Thakali", "Nepali", "Local food"],
    services: ["Lunch", "Dinner", "Group meals"],
    features: ["Family friendly", "Route meal", "Vegetarian options"],
    priceLevel: "Moderate",
    openingHours: "Confirm by inquiry",
    rating: 4.5,
    reviewCount: 21,
    featured: true,
    verificationStatus: "PUBLIC_LISTING",
    googleMapLink: "https://maps.google.com/?q=Restaurant+Birendranagar+Surkhet",
  },
  {
    slug: "ghantaghar-momo-corner",
    name: "Ghantaghar Momo Corner",
    type: "Fast Food",
    typeLabel: "Momo & Fast Food",
    area: "Ghantaghar",
    district: "Surkhet",
    address: "Clock tower area",
    shortDescription: "Quick momo, chowmein, tea, and snack stops around the city core.",
    longDescription: "Ghantaghar Momo Corner is a fast-food style public listing for quick city snacks. Confirm opening time and menu before relying on it for group plans.",
    image: images.momo,
    gallery: [images.momo, images.ghantaghar, images.cafe],
    cuisines: ["Momo", "Fast food", "Tea"],
    services: ["Snacks", "Takeaway", "Tea"],
    features: ["Quick stop", "City core", "Budget friendly"],
    priceLevel: "Budget",
    rating: 4.2,
    reviewCount: 16,
    featured: true,
    verificationStatus: "PUBLIC_LISTING",
    googleMapLink: "https://maps.google.com/?q=Momo+Ghantaghar+Surkhet",
  },
  {
    slug: "bulbule-lakeside-cafe",
    name: "Bulbule Lakeside Cafe",
    type: "Cafe",
    typeLabel: "Viewpoint Cafe",
    area: "Bulbule",
    district: "Surkhet",
    address: "Near Bulbule Lake",
    shortDescription: "Tea, coffee, light snacks, and easy food planning around Bulbule Lake.",
    longDescription: "Bulbule Lakeside Cafe is a lake-area cafe listing for evening walks and light snacks. It is useful for short Surkhet plans and family breaks.",
    image: images.bulbule,
    gallery: [images.bulbule, images.coffee, images.bheriBridge],
    cuisines: ["Coffee", "Tea", "Snacks"],
    services: ["Light meals", "Cafe", "Family stop"],
    features: ["Lake nearby", "Evening stop", "Traveler friendly"],
    priceLevel: "Budget",
    rating: 4.3,
    reviewCount: 14,
    featured: true,
    verificationStatus: "PUBLIC_LISTING",
    googleMapLink: "https://maps.google.com/?q=Bulbule+Lake+Cafe+Surkhet",
  },
  {
    slug: "cafes-near-city-core",
    name: "Cafes Near the City Core",
    type: "Cafe",
    typeLabel: "Cafe",
    area: "Birendranagar",
    district: "Surkhet",
    shortDescription: "Coffee, tea, light snacks, and planning breaks before moving onward.",
    longDescription: "City-core cafes give travelers a simple place to plan routes, wait for transport, and meet local contacts before moving toward Karnali districts.",
    image: images.cafe,
    gallery: [images.cafe, images.coffee, images.ghantaghar],
    cuisines: ["Coffee", "Bakery", "Tea"],
    services: ["Cafe", "Light snacks", "Planning break"],
    features: ["City access", "Wi-Fi possible", "Meetup friendly"],
    priceLevel: "Moderate",
    rating: 4.1,
    reviewCount: 12,
    featured: true,
    verificationStatus: "PUBLIC_LISTING",
    googleMapLink: "https://maps.google.com/?q=Cafe+Birendranagar+Surkhet",
  },
  {
    slug: "route-side-tea-and-snacks",
    name: "Route-side Tea and Snacks",
    type: "Tea Shop",
    typeLabel: "Route Tea Stop",
    area: "Gurase route",
    district: "Surkhet / Dailekh",
    shortDescription: "Small practical food stops for Gurase, Dailekh, and longer road journeys.",
    longDescription: "Route-side tea and snack stops are included for practical journey planning. They should be treated as flexible suggestions and confirmed locally on the day of travel.",
    image: images.tea,
    gallery: [images.tea, images.gurase, images.bheriBridge],
    cuisines: ["Tea", "Snacks", "Local food"],
    services: ["Tea stop", "Route snack", "Driver break"],
    features: ["Route-side", "Budget friendly", "Quick stop"],
    priceLevel: "Budget",
    verificationStatus: "PUBLIC_LISTING",
    googleMapLink: "https://maps.google.com/?q=Gurase+Tea+Stop",
  },
  {
    slug: "karnali-coffee-house",
    name: "Karnali Coffee House",
    type: "Cafe",
    typeLabel: "Coffee House",
    area: "Birendranagar",
    district: "Surkhet",
    shortDescription: "A modern coffee stop for travelers, students, and route planning conversations.",
    longDescription: "Karnali Coffee House is presented as a modern cafe-style listing for coffee, light bites, and calm planning time before longer travel.",
    image: images.coffee,
    gallery: [images.coffee, images.nightView, images.ghantaghar],
    cuisines: ["Coffee", "Bakery", "Snacks"],
    services: ["Coffee", "Light food", "Meetup"],
    features: ["Indoor seating", "Planning break", "Traveler friendly"],
    priceLevel: "Moderate",
    rating: 4.4,
    reviewCount: 17,
    featured: false,
    verificationStatus: "PUBLIC_LISTING",
  },
  {
    slug: "deuti-family-restaurant",
    name: "Deuti Family Restaurant",
    type: "Restaurant",
    typeLabel: "Family Restaurant",
    area: "Deuti Bajai",
    district: "Surkhet",
    shortDescription: "Family meals and local food options near one of Surkhet's key temple areas.",
    longDescription: "Deuti Family Restaurant is an inquiry-based food listing for visitors combining temple stops with simple local meals.",
    image: images.deutiBajai,
    gallery: [images.deutiBajai, images.restaurant, images.kakrebihar],
    cuisines: ["Nepali", "Local food", "Vegetarian"],
    services: ["Lunch", "Dinner", "Family meals"],
    features: ["Temple nearby", "Family friendly", "Local meals"],
    priceLevel: "Moderate",
    verificationStatus: "PUBLIC_LISTING",
    googleMapLink: "https://maps.google.com/?q=Deuti+Bajai+Restaurant+Surkhet",
  },
  {
    slug: "surkhet-bakery-and-cafe",
    name: "Surkhet Bakery and Cafe",
    type: "Bakery",
    typeLabel: "Bakery & Cafe",
    area: "Birendranagar",
    district: "Surkhet",
    shortDescription: "Bakery snacks, tea, and quick cafe food around the city area.",
    longDescription: "Surkhet Bakery and Cafe is useful for quick snacks, packed food, and lighter breaks between city errands or onward travel.",
    image: images.eventFood,
    gallery: [images.eventFood, images.cafe, images.ghantaghar],
    cuisines: ["Bakery", "Snacks", "Tea"],
    services: ["Bakery", "Cafe", "Takeaway"],
    features: ["Quick stop", "Packed snacks", "City access"],
    priceLevel: "Budget",
    verificationStatus: "PUBLIC_LISTING",
  },
  {
    slug: "bheri-route-food-stop",
    name: "Bheri Route Food Stop",
    type: "Restaurant",
    typeLabel: "Route Food Stop",
    area: "Bheri corridor",
    district: "Surkhet / Jajarkot route",
    shortDescription: "Simple meals and snacks for travelers moving along the Bheri corridor.",
    longDescription: "Bheri Route Food Stop is a route-focused public listing. Confirm timing, group food, and road condition before depending on it.",
    image: images.bheriBridge,
    gallery: [images.bheriBridge, images.bheriRiver, images.restaurant],
    cuisines: ["Local food", "Tea", "Snacks"],
    services: ["Route meal", "Tea", "Driver stop"],
    features: ["Route-side", "Group inquiry", "Local meals"],
    priceLevel: "Budget",
    verificationStatus: "PENDING",
    googleMapLink: "https://maps.google.com/?q=Bheri+River+food+stop",
  },
  {
    slug: "surkhet-event-and-party-venue",
    name: "Surkhet Event and Party Venue",
    type: "Event Venue",
    typeLabel: "Events & Party Venue",
    area: "Birendranagar",
    district: "Surkhet",
    shortDescription: "Inquiry-based group dining and event food support for families and teams.",
    longDescription: "Surkhet Event and Party Venue is included for group dining and event-style food inquiries. Final capacity, menu, and booking must be confirmed directly.",
    image: images.lounge,
    gallery: [images.lounge, images.eventFood, images.nightView],
    cuisines: ["Buffet", "Nepali", "Snacks"],
    services: ["Group dining", "Events", "Party menu"],
    features: ["Group friendly", "Event support", "Inquiry required"],
    priceLevel: "Premium",
    verificationStatus: "PUBLIC_LISTING",
  },
];

type FoodProviderSeed = [slug: string, name: string, typeLabel: string, area: string, cuisines: string[]];

const supplementalFoodSource: FoodProviderSeed[] = [
  ["4-to-9-cafe", "4 to 9 Cafe", "Cafe", "Siddhartha Multipurpose Co-operative, Birendranagar", ["Coffee", "Cafe food", "Breakfast"]],
  ["tauwa-coffee-shop", "Tauwa Coffee Shop", "Cafe", "Pipal Chautari Road, Birendranagar", ["Coffee", "Snacks", "Cafe"]],
  ["teapoint-surkhet", "Teapoint Surkhet", "Tea Shop", "Birendranagar", ["Tea", "Snacks", "Cafe"]],
  ["dream-light-bakery-cafe", "Dream Light Bakery Cafe Pvt. Ltd.", "Bakery", "Birendranagar", ["Bakery", "Cafe", "Snacks"]],
  ["shital-dairy", "Shital Dairy", "Cafe", "Birendranagar", ["Dairy", "Cafe", "Snacks"]],
  ["doredo-cafe", "DOREDO CAFE", "Cafe", "Birendranagar", ["Cafe", "Snacks"]],
  ["maarikaas-cafe", "Maarikaa's Cafe", "Cafe", "Birendranagar", ["Cafe", "Restaurant", "Snacks"]],
  ["chakati-lounge-and-cafe", "Chakati Lounge and Cafe", "Cafe Lounge", "Birendranagar", ["Cafe", "Lounge", "Restaurant"]],
  ["the-hub-cafe", "The Hub Cafe", "Cafe", "Birendranagar", ["Cafe", "Restaurant", "Snacks"]],
  ["chef-choice-restaurant-pizza-hut", "Chef Choice Restaurant & Pizza Hut", "Restaurant", "Birendranagar", ["Pizza", "Nepali", "Indian", "Bakery"]],
  ["zeyana-restaurant-and-bar", "Zeyana Restaurant & Bar", "Restaurant", "High School Road, Birendranagar", ["Cafe", "Diner", "Snacks"]],
  ["dfc-restaurant-and-bar", "DFC Restaurant & Bar", "Bar & Lounge", "Birendranagar", ["Nepali", "Indian", "Continental"]],
  ["goreto-family-restro-live-music-bar", "Goreto Family Restro & Live Music Bar", "Bar & Lounge", "Birendranagar", ["Nepali", "Snacks", "Continental"]],
  ["umbrella-restro-and-bar", "Umbrella Restro & Bar", "Bar & Lounge", "Birendranagar", ["Restaurant", "Snacks", "Beverage"]],
  ["sherpa-restaurant-and-bar", "Sherpa Restaurant & Bar", "Bar & Lounge", "Birendranagar", ["Nepali", "Snacks", "Tea"]],
  ["kaushik-garden-restaurant", "Kaushik Garden Restaurant", "Family Restaurant", "Birendranagar-8", ["Multi-cuisine", "Cafe", "Fast food"]],
  ["bhansa-green-cafe-and-restro", "Bhansa Green Cafe & Restro", "Restaurant", "Birendranagar-3", ["Nepali", "Cafe", "Snacks"]],
  ["the-rajdhani-cafe-and-restaurant", "The Rajdhani Cafe & Restaurant", "Restaurant", "Buddhapath, Surkhet", ["Nepali", "Indian", "Cafe"]],
  ["bagaicha-cottage", "Bagaicha Cottage", "Family Restaurant", "Birendranagar", ["Restaurant", "Local food", "Nepali"]],
  ["sundar-bagaicha-events-restaurant", "Sundar Bagaicha Events Restaurant", "Events Restaurant", "Birendranagar", ["Event food", "Nepali", "Restaurant"]],
  ["khadka-guest-house-and-resturant", "Khadka Guest House and Resturant", "Restaurant", "Birendranagar", ["Nepali", "Local food"]],
  ["thakali-restaurant", "Thakali Restaurant", "Local Food", "Birendranagar", ["Thakali", "Nepali", "Rice meal"]],
  ["tapari-momo", "Tapari Momo", "Momo", "Birendranagar", ["Momo", "Fast food", "Snacks"]],
  ["kathmandu-momo", "Kathmandu Momo", "Momo", "Ghantaghar Chowk, Birendranagar", ["Momo", "Fast food", "Snacks"]],
  ["dimsum-puri-fastfood-restaurant", "Dimsum Puri Fastfood Restaurant", "Fast Food", "New Road, Surkhet", ["Fast food", "Biryani", "Momo"]],
  ["punte-restaurent-and-grill-house", "Punte Restaurent & Grill House", "Fast Food", "Simtali Chowk, Surkhet", ["Grill", "Fast food", "Nepali"]],
  ["sasa-bhutu", "Sasa Bhutu", "Restaurant", "Birendranagar", ["Nepali", "Snacks", "Restaurant"]],
  ["fish-cottage", "Fish Cottage", "Restaurant", "Birendranagar", ["Fish", "Nepali", "Local food"]],
  ["dahri-bhaiko-chiya-pasal", "Dahri Bhaiko Chiya Pasal", "Tea Shop", "Latikoili, Surkhet", ["Tea", "Snacks"]],
  ["chahana-cottage-gothikada-surkhet", "Chahana Cottage, Gothikada, Surkhet", "Viewpoint Cafe", "Gothikada", ["Local food", "Snacks", "Cafe"]],
  ["surkhet-baral-house", "Surkhet Baral House", "Bar & Lounge", "Birendranagar-8", ["Snacks", "Beverage", "Restaurant"]],
  ["mega-restaurant-and-party-palace", "Mega Restaurant & Party Palace", "Party Palace", "Dhamalachwok, Surkhet", ["Event food", "Nepali", "Restaurant"]],
];

const supplementalFoodSeeds: FoodProvider[] = supplementalFoodSource.map(([slug, name, typeLabel, area, cuisines], index) => ({
  slug,
  name,
  type: typeLabel,
  typeLabel,
  area,
  district: "Surkhet",
  address: area,
  shortDescription: `${name} is a Pahuna food listing for travelers looking for ${cuisines.slice(0, 2).join(" and ")} around Surkhet.`,
  longDescription: `${name} is adapted into the current Pahuna food catalogue as an inquiry-safe public listing. Confirm opening hours, menu, group capacity, and exact location before planning around it.`,
  image: [images.cafe, images.coffee, images.food, images.momo, images.restaurant, images.lounge, images.eventFood][index % 7],
  gallery: [
    [images.cafe, images.coffee, images.tea][index % 3],
    [images.food, images.momo, images.restaurant][index % 3],
    [images.bulbule, images.ghantaghar, images.nightView][index % 3],
  ],
  cuisines,
  services: ["Dine-in inquiry", "Menu confirmation", "Traveler food stop"],
  features: [typeLabel, "Public listing", index % 2 === 0 ? "Quick stop" : "Group inquiry"],
  priceLevel: index % 5 === 0 ? "Premium" : index % 2 === 0 ? "Budget" : "Moderate",
  featured: index < 8 || typeLabel.includes("Viewpoint"),
  verificationStatus: "PUBLIC_LISTING",
  googleMapLink: `https://maps.google.com/?q=${encodeURIComponent(`${name} ${area}`)}`,
}));

const foodSlugSet = new Set(foodProviders.map((provider) => provider.slug));
foodProviders.push(...supplementalFoodSeeds.filter((provider) => !foodSlugSet.has(provider.slug)));

export const foodHighlights: FeatureCard[] = foodProviders.slice(0, 3).map((provider) => ({
  title: provider.name,
  slug: provider.slug,
  eyebrow: provider.typeLabel,
  description: provider.shortDescription,
  href: `/food/${provider.slug}`,
  image: provider.image,
}));

export const destinations: FeatureCard[] = [
  {
    title: "Rara Lake",
    eyebrow: "Mugu",
    description: "A dream Karnali destination that needs planning, buffer days, and confirmed logistics.",
    href: "/destinations#rara",
    image: images.rara,
  },
  {
    title: "Shey Phoksundo",
    eyebrow: "Dolpa",
    description: "A remote blue lake experience for travelers ready for tougher logistics.",
    href: "/destinations#phoksundo",
    image: images.phoksundo,
  },
  {
    title: "Kupinde Daha",
    eyebrow: "Salyan",
    description: "A peaceful lake extension from Surkhet for flexible regional plans.",
    href: "/destinations#kupinde",
    image: images.kupinde,
  },
];

export const routeCards = [
  {
    route: "Kathmandu to Surkhet",
    mode: "Flight or road",
    note: "Best entry route for first-time Karnali travelers.",
    status: "Confirm schedule",
  },
  {
    route: "Surkhet to Rara",
    mode: "Road / jeep mix",
    note: "Plan buffer days for road, weather, and overnight stops.",
    status: "Season dependent",
  },
  {
    route: "Surkhet to Dailekh",
    mode: "Road",
    note: "Useful short cultural extension from Surkhet.",
    status: "Moderate",
  },
  {
    route: "Surkhet to Dolpa / Phoksundo",
    mode: "Flight / road mix",
    note: "Remote route with operator and weather dependency.",
    status: "Needs confirmation",
  },
];

export const galleryItems = [
  { title: "Bulbule Lake", category: "Surkhet", image: images.bulbule, alt: "Bulbule Lake in Surkhet" },
  { title: "Kakrebihar ruins", category: "Surkhet", image: images.kakrebihar, alt: "Kakrebihar heritage site" },
  { title: "Gurase View Tower", category: "Surkhet", image: images.gurase, alt: "Gurase viewpoint and tower" },
  { title: "Bheri River Bridge", category: "Surkhet", image: images.bheriBridge, alt: "Bheri River Bridge near Surkhet" },
  { title: "Rara Lake", category: "Karnali", image: images.rara, alt: "Rara Lake in Karnali" },
  { title: "Phoksundo Lake", category: "Karnali", image: images.phoksundo, alt: "Phoksundo Lake in Dolpa" },
  { title: "Karnali River", category: "Karnali", image: images.karnaliRiver, alt: "Karnali River landscape" },
  { title: "Tharu Cultural Evening", category: "Culture", image: images.tharuCulture, alt: "Tharu cultural performance" },
  { title: "Camping routes", category: "Adventure", image: images.camping, alt: "Camping experience in Karnali" },
];
