import {
  BadgeCheck,
  Camera,
  CircleDollarSign,
  Compass,
  Flame,
  Heart,
  Landmark,
  Leaf,
  Map,
  Mountain,
  ShieldCheck,
  Sparkles,
  Utensils,
  Waves,
} from "lucide-react";

export const PASSPORT_BADGES = [
  {
    id: "surkhet-starter",
    name: "Surkhet Starter",
    description: "Start with Birendranagar, Bulbule, Kakrebihar, and Deuti Bajai.",
    icon: Map,
  },
  {
    id: "rara-dreamer",
    name: "Rara Dreamer",
    description: "Dream up a Rara or Mugu route with buffer time.",
    icon: Leaf,
  },
  {
    id: "sinja-story-hunter",
    name: "Sinja Story Hunter",
    description: "Follow culture, Jumla, Sinja, and local history routes.",
    icon: Landmark,
  },
  {
    id: "phoksundo-explorer",
    name: "Phoksundo Explorer",
    description: "Plan carefully for Dolpa, Ringmo, and Phoksundo routes.",
    icon: Mountain,
  },
  {
    id: "panchakoshi-pilgrim",
    name: "Panchakoshi Pilgrim",
    description: "Build a spiritual Dailekh and Panchakoshi circuit.",
    icon: Sparkles,
  },
  {
    id: "bheri-adventure-seeker",
    name: "Bheri Adventure Seeker",
    description: "Explore river, rafting, and adventure-friendly routes.",
    icon: Waves,
  },
  {
    id: "karnali-grand-circuit",
    name: "Karnali Grand Circuit",
    description: "Link Surkhet with multi-district Karnali planning.",
    icon: BadgeCheck,
  },
] as const;

export type PassportBadgeId = (typeof PASSPORT_BADGES)[number]["id"];

export const VIBE_OPTIONS = [
  {
    id: "peaceful",
    label: "Peaceful",
    icon: Leaf,
    destinations: ["Bulbule Lake", "Barahatal", "Rara Lake"],
    itineraryType: "Lake, nature, and slow travel",
    duration: "2-4 days",
    difficulty: "Easy to Moderate",
    budget: "Standard",
    badgeId: "rara-dreamer",
    href: "/destinations",
  },
  {
    id: "adventure",
    label: "Adventure",
    icon: Flame,
    destinations: ["Bheri River", "Rara route", "Phoksundo", "Limi Valley"],
    itineraryType: "River, trekking, and remote route planning",
    duration: "5+ days",
    difficulty: "Moderate to Hard",
    budget: "Standard to Premium",
    badgeId: "bheri-adventure-seeker",
    href: "/routes",
  },
  {
    id: "culture",
    label: "Culture",
    icon: Landmark,
    destinations: ["Kakrebihar", "Sinja Valley", "Dullu", "Jumli Marsi culture"],
    itineraryType: "Heritage and local story route",
    duration: "2-5 days",
    difficulty: "Easy to Moderate",
    budget: "Budget to Standard",
    badgeId: "sinja-story-hunter",
    href: "/destinations",
  },
  {
    id: "family",
    label: "Family",
    icon: Heart,
    destinations: ["Birendranagar", "Bulbule Lake", "Deuti Bajai", "Kakrebihar"],
    itineraryType: "Short, light, family-friendly Surkhet trip",
    duration: "1-3 days",
    difficulty: "Easy",
    budget: "Budget to Standard",
    badgeId: "surkhet-starter",
    href: "/explore",
  },
  {
    id: "budget",
    label: "Budget",
    icon: CircleDollarSign,
    destinations: ["Surkhet city", "Dailekh short circuit", "local lodges"],
    itineraryType: "Road-first short Karnali plan",
    duration: "1-3 days",
    difficulty: "Easy to Moderate",
    budget: "Budget",
    badgeId: "surkhet-starter",
    href: "/trip-planner",
  },
  {
    id: "premium",
    label: "Premium",
    icon: ShieldCheck,
    destinations: ["Surkhet flight", "resort stays", "guided Rara", "Humla custom route"],
    itineraryType: "Comfort-focused custom planning",
    duration: "4-7 days",
    difficulty: "Moderate to Hard",
    budget: "Premium",
    badgeId: "karnali-grand-circuit",
    href: "/ai-trip-planner",
  },
  {
    id: "spiritual",
    label: "Spiritual",
    icon: Sparkles,
    destinations: ["Deuti Bajai", "Panchakoshi", "Chandannath", "Yalbang Monastery"],
    itineraryType: "Temple and monastery route",
    duration: "2-5 days",
    difficulty: "Easy to Moderate",
    budget: "Budget to Standard",
    badgeId: "panchakoshi-pilgrim",
    href: "/destinations",
  },
  {
    id: "hidden",
    label: "Hidden Places",
    icon: Compass,
    destinations: ["Barahatal", "Pachal Jharana", "Barekot", "Tila Valley"],
    itineraryType: "Lesser-known village and viewpoint route",
    duration: "3-6 days",
    difficulty: "Moderate to Hard",
    budget: "Standard",
    badgeId: "karnali-grand-circuit",
    href: "/destinations",
  },
  {
    id: "food",
    label: "Local Food",
    icon: Utensils,
    destinations: ["Birendranagar food stops", "Jumli Marsi culture", "Jumla apple farms"],
    itineraryType: "Food, market, and culture route",
    duration: "2-4 days",
    difficulty: "Easy to Moderate",
    budget: "Budget to Standard",
    badgeId: "sinja-story-hunter",
    href: "/itineraries",
  },
] as const;

export const BUDGET_OPTIONS = [
  {
    value: 10000,
    label: "NPR 10,000",
    title: "1-2 day Surkhet local trip",
    bullets: [
      "Bulbule Lake, Deuti Bajai, and Kakrebihar",
      "Budget stay or day trip",
      "Best for students, solo travelers, and local visitors",
    ],
    chips: ["Surkhet", "Budget stay", "Short trip"],
    ctaBudget: "Under NPR 10,000",
  },
  {
    value: 25000,
    label: "NPR 25,000",
    title: "2-3 day Surkhet + Dailekh plan",
    bullets: [
      "Family-friendly Surkhet city and Panchakoshi route",
      "Standard local stay and road transport",
      "Best for family or couple short trips",
    ],
    chips: ["Dailekh", "Family", "Road route"],
    ctaBudget: "NPR 20,000 - 35,000",
  },
  {
    value: 50000,
    label: "NPR 50,000",
    title: "4-5 day Surkhet to Rara planning range",
    bullets: [
      "Road route via Kalikot/Jumla depending on transport",
      "Requires route and stay confirmation",
      "Best for nature and photography travelers",
    ],
    chips: ["Rara", "Photography", "Route buffer"],
    ctaBudget: "NPR 35,000+",
  },
  {
    value: 100000,
    label: "NPR 100,000",
    title: "Remote Karnali custom planning",
    bullets: [
      "Guided Rara, Humla, or Phoksundo-style planning",
      "Better for groups, private transport, or route buffer",
      "Requires custom confirmation due to flights, weather, and road conditions",
    ],
    chips: ["Humla", "Phoksundo", "Custom route"],
    ctaBudget: "NPR 35,000+",
  },
] as const;

export const LOCAL_TIPS = {
  general: [
    "Keep a buffer day for Rara, Dolpa, and Humla.",
    "Remote flights are weather-dependent.",
    "Carry cash outside major towns.",
    "Confirm road condition before long Karnali routes.",
  ],
  surkhet: [
    "Visit Bulbule in the evening.",
    "Pair Kakrebihar with Deuti Bajai for an easy culture day.",
    "Start family trips with Surkhet and Dailekh before remote routes.",
    "Try local food stops in Birendranagar before onward travel.",
  ],
  remote: [
    "Morning departures are better for hill-road travel.",
    "Avoid tight schedules for Phoksundo and Humla trips.",
    "For trekking routes, use local guides and confirm permits/support.",
    "Carry warm clothes for high-altitude destinations.",
  ],
  ai: [
    "Use flexible dates for weather-sensitive routes.",
    "Add your travel style so Pahuna can suggest better stays.",
    "Ask Pahuna to verify route, fare, and operator schedule before booking.",
    "Remote routes need buffer days and local confirmation.",
  ],
} as const;

export const CONFIDENCE_KEYWORDS = {
  easy: ["Surkhet", "Birendranagar", "Bulbule", "Deuti Bajai", "Kakrebihar"],
  moderate: ["Dailekh", "Salyan", "Jajarkot", "Jumla", "Sinja", "Rara"],
  hard: ["Dolpa", "Phoksundo", "Humla", "Limi", "multi-district"],
  weather: ["flight", "Humla", "Dolpa", "Mugu", "Rara", "Phoksundo", "monsoon"],
  family: ["Surkhet", "Dailekh", "family", "Bulbule", "Deuti Bajai"],
  guide: ["Dolpa", "Phoksundo", "Humla", "Limi", "trek", "remote", "Rara"],
} as const;

